/**
 * Utility for stripping Canvas LMS external site link artifacts from HTML and plain text.
 * Canvas Rich Content Editor automatically injects screenreader text and icons such as
 * "(Links to an external site.)", "Links to external site.", or <span class="screenreader-only">
 * which do not appear in the native Canvas UI and should be stripped.
 */

// Matches screenreader-only and icon elements generated by Canvas
const CANVAS_SCREENREADER_TAGS =
	/<(?:span|i)[^>]*class=["'][^"']*(?:screenreader-only|ui-icon-extlink|ui-icon)[^"']*["'][^>]*>[\s\S]*?<\/(?:span|i)>/gi;

// Matches elements with title containing "Links to (an )?external site"
const CANVAS_TITLE_TAGS =
	/<(?:span|i|a)[^>]*title=["'][^"']*Links to (?:an\s+)?external site[^"']*["'][^>]*>[\s\S]*?<\/(?:span|i|a)>/gi;

// Matches text variants: "(Links to an external site.)", "Links to external site.", "[Links to external site]", etc.
const CANVAS_EXTERNAL_LINK_TEXT_REGEX =
	/(?:&nbsp;|&#160;|\u00a0|\s)*[\(\[]?\s*Links to (?:an\s+)?external site\.?\s*[\)\]]?/gi;

/**
 * Strips Canvas external link text and screenreader artifacts from an HTML string while preserving markup.
 */
export function cleanCanvasHtml(rawHtml: string): string {
	if (!rawHtml) return "";

	let cleaned = rawHtml;

	// 1. Remove screenreader spans/icons and their content
	cleaned = cleaned.replace(CANVAS_SCREENREADER_TAGS, "");
	cleaned = cleaned.replace(CANVAS_TITLE_TAGS, "");

	// 2. Remove remaining text patterns
	cleaned = cleaned.replace(CANVAS_EXTERNAL_LINK_TEXT_REGEX, "");

	return cleaned;
}

/**
 * Strips HTML tags and Canvas external link text to produce clean, plain text for summaries/tooltips.
 */
export function cleanCanvasText(rawText: string): string {
	if (!rawText) return "";

	// 1. Remove screenreader spans before stripping tags
	let text = rawText.replace(CANVAS_SCREENREADER_TAGS, "");
	text = text.replace(CANVAS_TITLE_TAGS, "");

	// 2. Strip HTML tags
	text = text.replace(/<[^>]*>?/gm, " ");

	// 3. Decode common HTML entities
	text = text
		.replace(/&nbsp;/gi, " ")
		.replace(/&#160;/g, " ")
		.replace(/&amp;/gi, "&")
		.replace(/&lt;/gi, "<")
		.replace(/&gt;/gi, ">")
		.replace(/&quot;/gi, '"')
		.replace(/&#39;/g, "'")
		.replace(/&apos;/gi, "'");

	// 4. Remove external link text artifacts
	text = text.replace(CANVAS_EXTERNAL_LINK_TEXT_REGEX, "");

	// 5. Clean up extra whitespace
	return text.replace(/[ \t]+/g, " ").replace(/\n\s*\n/g, "\n\n").trim();
}
